name: ASP.NET Core CI

env:
  source_path: ./src
  
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-16.04, ubuntu-18.04, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      working-directory: ${{ env.source_path }}
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ${{ env.source_path }}
      run: dotnet test --configuration Release
    - name: Run Publish
      working-directory: ${{ env.source_path }}
      run: dotnet publish --configuration Release
