name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
          artifact_path: ./Kongo/bin/${{matrix.os}}/artifacts
          source_path: ./src
    strategy:
      matrix:
        os: [windows-latest, ubuntu-16.04, ubuntu-18.04, macOS-latest]
               
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      working-directory: ${{ env.source_path }}
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ${{ env.source_path }}
      run: dotnet test --configuration Release
    - name: Run Publish
      working-directory: ${{ env.source_path }}
      run: 
        mkdir ${{ env.artifact_path }}
        dotnet publish --configuration Release --output ${{ env.artifact_path }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Kongo-${{ matrix.os }}
        path: ${{ env.artifact_path }}
